version: '3'
services:
  python:
    container_name: python
    build: ./docker/
    env_file:
      - ./.env
    tty: true
    stdin_open: true
    working_dir: '/root/python/'
    volumes:
      - ./log:/root/log
      - ./src/:/root/python
